//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arabalar
    {
        public int ArabaNo { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public decimal Fiyat { get; set; }
        public Nullable<int> BayiNo { get; set; }
    
        public virtual Bayiler Bayiler { get; set; }
    }
}
