//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bayiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bayiler()
        {
            this.Arabalar = new HashSet<Arabalar>();
        }
    
        public int BayiNo { get; set; }
        public string BayiAdi { get; set; }
        public string BayiAdres { get; set; }
        public string BayiCiro { get; set; }
        public string Adet { get; set; }
        public int KullaniciNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arabalar> Arabalar { get; set; }
    }
}
