//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_PROJE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int PersonelNo { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<int> Yas { get; set; }
        public string Meslek { get; set; }
        public string Mezuniyet { get; set; }
        public Nullable<decimal> Maas { get; set; }
        public Nullable<int> DepartmanNo { get; set; }
        public Nullable<int> SubeID { get; set; }
    
        public virtual Departman Departman { get; set; }
        public virtual Şubeler Şubeler { get; set; }
    }
}
